CREATE TABLE account (
    account_no NUMBER PRIMARY KEY,
    customer_name VARCHAR2(100),
    account_type VARCHAR2(20),
    mobile VARCHAR2(10),
    email VARCHAR2(100),
    address VARCHAR2(200),
    password VARCHAR2(50),
    balance NUMBER(10,2)
);

CREATE TABLE transaction_history (
    transaction_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_no NUMBER,
    transaction_type VARCHAR2(20),
    amount NUMBER(10,2),
    transaction_date DATE DEFAULT SYSDATE
);

DESC transaction_history;

SELECT * FROM account;